### ISSUE TITLE
[CsvImport+] Stopped import or undo import due to error Uncaught ArgumentCountError: Too few arguments to function CsvImportPlus_Import::_getRecordFromIdentifier()

### ISSUE THREAD

**Issue by pabolitox** [Daniel-KM/Omeka-plugin-CsvImportPlus#20]
Hello,

when trying to use the extension, I got an exception
I am working in OMEKA 2.7.1
CENTOS 7.9
PHP 7.4

This are the logs on the error:

```
2022-01-28T10:46:40+00:00 DEBUG (7): [CsvImport+][#7] Running item import loop. Memory usage: 7483376.
2022-01-28T10:46:40+00:00 ERR (3): [CsvImport+][#7] Stopped import or undo import due to error [file /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/Import.php, line 1613]: Uncaught ArgumentCountError: Too few arguments to function CsvImportPlus_Import::_getRecordFromIdentifier(), 3 passed in /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/Import.php on line 922 and exactly 4 expected in /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/Import.php:1613
Stack trace:
#0 /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/Import.php(922): CsvImportPlus_Import->_getRecordFromIdentifier()
#1 /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/Import.php(724): CsvImportPlus_Import->_manageFromMappedRow()
#2 /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/Import.php(369): CsvImportPlus_Import->_importLoop()
#3 /var/www/html/plugins/CsvImportPlus/models/CsvImportPlus/ImportTask.php(45): CsvImportPlus_Import->start()
#4 /var/www/html/application/libraries/Omeka/Job/Process/Wrapper.php(29): CsvImportPlus_ImportTask->perform()
#5 /var/www/html/application/scripts/background.php(61): Omeka_Job_Process_Wrapper->run()
#6 {main}
  thrown
```

the csvimport from omeka works fine what makes me believe that .csv file, upload errors or similar issues can be a priori ruled out.
If anyone could please kindly give me any ideas on where to start troubleshooting this error, what the possible root causes are or how to get some more information in the logs to point me in the good direction?

this is what I got in application/config/config.ini
debug.exceptions = true
log.errors = true
log.priority = Zend_Log::DEBUG

Thanks in advance
